services:

  rabbitmq:
    image: rabbitmq:4.3-management
    container_name: rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: monitoring
      RABBITMQ_DEFAULT_PASS: monitoring123

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

    restart: unless-stopped

    networks:
      - monitoring-network


  agent1:
    build: .
    container_name: agent1

    environment:
      AGENT_NAME: agent-1
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: monitoring
      RABBITMQ_PASSWORD: monitoring123
      RABBITMQ_QUEUE: network.metrics
      COLLECT_INTERVAL_MS: 5000

    depends_on:
      rabbitmq:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - monitoring-network


  agent2:
    build: .
    container_name: agent2

    environment:
      AGENT_NAME: agent-2
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: monitoring
      RABBITMQ_PASSWORD: monitoring123
      RABBITMQ_QUEUE: network.metrics
      COLLECT_INTERVAL_MS: 5000

    depends_on:
      rabbitmq:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - monitoring-network


  agent3:
    build: .
    container_name: agent3

    environment:
      AGENT_NAME: agent-3
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: monitoring
      RABBITMQ_PASSWORD: monitoring123
      RABBITMQ_QUEUE: network.metrics
      COLLECT_INTERVAL_MS: 5000

    depends_on:
      rabbitmq:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - monitoring-network


  agent4:
    build: .
    container_name: agent4

    environment:
      AGENT_NAME: agent-4
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: monitoring
      RABBITMQ_PASSWORD: monitoring123
      RABBITMQ_QUEUE: network.metrics
      COLLECT_INTERVAL_MS: 5000

    depends_on:
      rabbitmq:
        condition: service_healthy

    restart: unless-stopped

    networks:
      - monitoring-network


  metrics-consumer:
    build: .
    container_name: metrics-consumer

    command:
      - java
      - -cp
      - /app/app.jar
      - ru.course.monitoring.MetricsConsumerMain

    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: monitoring
      RABBITMQ_PASSWORD: monitoring123
      RABBITMQ_QUEUE: network.metrics
      VICTORIA_URL: http://victoriametrics:8428/api/v1/import/prometheus

    depends_on:
      rabbitmq:
        condition: service_healthy

      victoriametrics:
        condition: service_started

    restart: unless-stopped

    networks:
      - monitoring-network


  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.152.0
    container_name: victoriametrics

    # Для диагностики можно временно открыть:
    # ports:
    #   - "8428:8428"

    volumes:
      - victoria-data:/victoria-metrics-data

    command:
      - "-storageDataPath=/victoria-metrics-data"
      - "-retentionPeriod=1d"

    restart: unless-stopped

    networks:
      - monitoring-network


  grafana:
    image: grafana/grafana:13.2.1
    container_name: grafana

    # ports:
    #   - "3000:3000"

    environment:
      GF_SERVER_ROOT_URL: http://localhost/grafana/
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"

    volumes:
      - grafana-data:/var/lib/grafana

    depends_on:
      - victoriametrics

    restart: unless-stopped

    networks:
      - monitoring-network


  nginx:
    image: nginx:alpine
    container_name: nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - grafana

    restart: unless-stopped

    networks:
      - monitoring-network


volumes:

  victoria-data:
  grafana-data:
  rabbitmq-data:


networks:

  monitoring-network:
    driver: bridge